name: End-to-end tests
on:   
  push: 
  workflow_dispatch: 

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configurar Java (necessário para Allure)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Especifica a distribuição do JDK

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Executar os testes com Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          env: allure=true
        continue-on-error: true

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Ensure gh-pages branch exists
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history