name: End-to-end tests
on:   
  push: 
  workflow_dispatch: 

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configurar Java (necessário para Allure)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Especifica a distribuição do JDK

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Restaurar o cache de histórico do Allure
      - name: Restore Allure History
        uses: actions/cache@v3
        with:
          path: allure-results/history
          key: allure-history-${{ github.ref }}
          restore-keys: allure-history-

      # Executar os testes com Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          env: allure=true
        continue-on-error: true

      - name: Verificar se allure-results foi gerado
        run: |
          ls -la allure-results

      # Gerar o relatório Allure
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean

      # Copiar arquivos de histórico e remover antigos
      - name: Copy Allure History
        run: |
          rm -rf allure-results/history
          cp -r allure-report/history allure-results/

      # Atualizar o cache de histórico do Allure
      - name: Cache Allure History
        uses: actions/cache@v3
        with:
          path: allure-results/history
          key: allure-history-${{ github.ref }}

      # Publicar os relatórios Allure como artefato
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # Publicar os relatórios em GitHub Pages (opcional)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report